import { test,expect } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { sdkSession } from "./session";
import { openInspector } from "../core-e2e/presentation";
test("B1 SDK manager/staff fact flow, current assignment revocation and tenant/foreign denial",async({browser})=>{
 const tenant=await sdkSession(browser),manager=await sdkSession(browser,"manager"),staff=await sdkSession(browser,"staff"),foreign=await sdkSession(browser,"otherManager");
 try{
  const {admin,fixture}=tenant,property=randomUUID(),unit=randomUUID(),occ=randomUUID(),assignment=randomUUID();
  expect((await admin.query("SELECT shobj_description(oid,'pg_database') marker FROM pg_database WHERE datname=current_database()")).rows[0].marker).toBe("CORE_FLOW_SYNTHETIC_LOCAL");
  await admin.query("INSERT INTO app.property(id,org_id,status) VALUES($1,$2,'ACTIVE')",[property,fixture.orgA]);await admin.query("INSERT INTO core_flow.building_context(org_id,property_id,body) SELECT org_id,$1::uuid,body||jsonb_build_object('id',($1::uuid)::text,'displayName','합성 정비 격리 건물') FROM core_flow.building_context WHERE property_id=$2",[property,fixture.propertyA]);
  await admin.query("INSERT INTO app.unit(id,org_id,property_id,label,status) VALUES($1,$2,$3,'합성 정비 격리 호실','ACTIVE')",[unit,fixture.orgA,property]);await admin.query("INSERT INTO app.occupancy(id,org_id,unit_id,starts_at,status) VALUES($1,$2,$3,clock_timestamp(),'ACTIVE')",[occ,fixture.orgA,unit]);await admin.query("INSERT INTO app.occupancy_member(org_id,occupancy_id,user_id,joined_at,status) VALUES($1,$2,$3,clock_timestamp(),'ACTIVE')",[fixture.orgA,occ,tenant.account.userId]);
  const made=await tenant.context.request.post("/api/v2/core/tickets",{headers:tenant.headers,data:{unitId:unit,issueType:"LEAK",rawUserText:"합성 B1 정비 이력"}});expect(made.status()).toBe(201);const id=(await made.json()).ticketId,path=`/api/v2/core/manager/tickets/${id}/maintenance-fact`,list=`/api/v2/core/manager/units/${unit}/maintenance-timeline`;
  for(const status of ["IN_PROGRESS","COMPLETED"])expect((await manager.context.request.post(`/api/v2/core/tickets/${id}/handling`,{headers:manager.headers,data:{status,message:"합성 B1 처리",...(status==="COMPLETED"?{expectedCommunicationVersion:0}:{})}})).status()).toBe(200);
  expect((await staff.context.request.get(list,{headers:staff.headers})).status()).toBe(404);expect((await staff.context.request.post(path,{headers:staff.headers,data:{clientRequestId:randomUUID(),actionKind:"REPAIR",componentLabel:null}})).status()).toBe(404);
  await admin.query("INSERT INTO app.property_assignment(id,org_id,membership_id,property_id,status) VALUES($1,$2,$3,$4,'ACTIVE')",[assignment,fixture.orgA,staff.account.membershipId,property]);
  const page=await staff.context.newPage();await page.setViewportSize({width:390,height:844});await page.goto("/core");await page.locator(`[data-ticket-id="${id}"] [data-open-ticket]`).click();await openInspector(page);const editor=page.getByRole("region",{name:"호실 정비 사실 기록",exact:true});
  await editor.getByLabel("정비 작업 종류").selectOption("REPAIR");const posted=page.waitForResponse(r=>r.url().endsWith(path)&&r.request().method()==="POST");await editor.getByRole("button",{name:"정비 사실 저장",exact:true}).click();const response=await posted;expect(response.status()).toBe(201);const fact=await response.json(),input=response.request().postDataJSON(),correctPath=`/api/v2/core/manager/maintenance-facts/${fact.factId}/corrections`,correction={clientRequestId:randomUUID(),expectedCurrentFactId:fact.factId,actionKind:"ADJUSTMENT",componentLabel:null,correctionReason:"OTHER"};
  const corrected=await staff.context.request.post(correctPath,{headers:staff.headers,data:correction});expect(corrected.status()).toBe(201);
  for(const actor of [tenant,foreign]){const status=actor===tenant?403:404;for(const p of [path,list]){const r=await actor.context.request.get(p,{headers:actor.headers});expect(r.status()).toBe(status);expect(await r.text()).not.toContain(fact.factId);}expect((await actor.context.request.post(path,{headers:actor.headers,data:input})).status()).toBe(status);expect((await actor.context.request.post(correctPath,{headers:actor.headers,data:correction})).status()).toBe(status);}
  for(const p of [path,correctPath])expect((await staff.context.request.post(p,{headers:{...staff.headers,"x-b1-csrf":"invalid"},data:p===path?input:correction})).status()).toBe(403);
  await editor.getByRole("button",{name:"호실 이력에서 보기",exact:true}).click();await expect(page.getByRole("region",{name:"호실 정비 이력",exact:true}).getByText("조정",{exact:false})).toBeVisible();
  await admin.query("UPDATE app.property_assignment SET status='ENDED',ended_at=clock_timestamp() WHERE id=$1",[assignment]);
  await page.getByRole("button",{name:"이력 다시 불러오기",exact:true}).click();await expect(page.getByRole("region",{name:"호실 정비 이력",exact:true})).toHaveCount(0);await expect(page.getByRole("region",{name:"선택한 접수",exact:true})).toHaveCount(0);
  for(const p of [path,list])expect((await staff.context.request.get(p,{headers:staff.headers})).status()).toBe(404);expect((await staff.context.request.post(path,{headers:staff.headers,data:input})).status()).toBe(404);expect((await staff.context.request.post(correctPath,{headers:staff.headers,data:correction})).status()).toBe(404);
  expect((await manager.context.request.get(path,{headers:manager.headers})).status()).toBe(200);
 }finally{await tenant.close();await manager.close();await staff.close();await foreign.close();}
});
test("new occupancy member cannot read manager facts or old source after isolated unit turnover",async({browser})=>{
 const tenant=await sdkSession(browser),manager=await sdkSession(browser,"manager"),replacement=await sdkSession(browser,"tenantOther");
 try{const {admin,fixture}=tenant,unit=randomUUID(),occ=randomUUID(),member=randomUUID();
  await admin.query("INSERT INTO app.unit(id,org_id,property_id,label,status) VALUES($1,$2,$3,$4,'ACTIVE')",[unit,fixture.orgA,fixture.propertyA,"합성 정비 교체 호실 "+unit]);await admin.query("INSERT INTO app.occupancy(id,org_id,unit_id,starts_at,status) VALUES($1,$2,$3,clock_timestamp(),'ACTIVE')",[occ,fixture.orgA,unit]);await admin.query("INSERT INTO app.occupancy_member(id,org_id,occupancy_id,user_id,joined_at,status) VALUES($1,$2,$3,$4,clock_timestamp(),'ACTIVE')",[member,fixture.orgA,occ,tenant.account.userId]);
  const r=await tenant.context.request.post("/api/v2/core/tickets",{headers:tenant.headers,data:{unitId:unit,issueType:"HEATING",rawUserText:"합성 교체 전 정비"}});expect(r.status()).toBe(201);const id=(await r.json()).ticketId,path=`/api/v2/core/manager/tickets/${id}/maintenance-fact`;
  for(const status of ["IN_PROGRESS","COMPLETED"])expect((await manager.context.request.post(`/api/v2/core/tickets/${id}/handling`,{headers:manager.headers,data:{status,message:"합성 완료",...(status==="COMPLETED"?{expectedCommunicationVersion:0}:{})}})).status()).toBe(200);
  const created=await manager.context.request.post(path,{headers:manager.headers,data:{clientRequestId:randomUUID(),actionKind:"INSPECTION",componentLabel:"합성 밸브"}});expect(created.status()).toBe(201);const fact=await created.json();
  await admin.query("UPDATE app.occupancy_member SET status='ENDED',ended_at=clock_timestamp() WHERE id=$1",[member]);await admin.query("INSERT INTO app.occupancy_member(org_id,occupancy_id,user_id,joined_at,status) VALUES($1,$2,$3,clock_timestamp(),'ACTIVE')",[fixture.orgA,occ,replacement.account.userId]);
  expect((await replacement.context.request.get(`/api/v2/core/tickets/${id}`,{headers:replacement.headers})).status()).toBe(404);
  for(const p of [path,`/api/v2/core/manager/units/${unit}/maintenance-timeline`])expect((await replacement.context.request.get(p,{headers:replacement.headers})).status()).toBe(403);
  expect((await replacement.context.request.post(path,{headers:replacement.headers,data:{clientRequestId:randomUUID(),actionKind:"REPAIR",componentLabel:null}})).status()).toBe(403);expect((await replacement.context.request.post(`/api/v2/core/manager/maintenance-facts/${fact.factId}/corrections`,{headers:replacement.headers,data:{clientRequestId:randomUUID(),expectedCurrentFactId:fact.factId,actionKind:"OTHER",componentLabel:null,correctionReason:"OTHER"}})).status()).toBe(403);
  const page=await replacement.context.newPage();await page.goto("/core");await page.getByLabel("건물·호실",{exact:true}).selectOption(unit);await expect(page.locator(`[data-ticket-id="${id}"]`)).toHaveCount(0);await expect(page.getByRole("navigation",{name:"관리자 보기"})).toHaveCount(0);expect((await manager.context.request.get(path,{headers:manager.headers})).status()).toBe(200);
 }finally{await tenant.close();await manager.close();await replacement.close();}
});
